UBICACIONES = {
    # ── Región Metropolitana ──────────────────────────────
    "lascondes":       "Las Condes",
    "las_condes":      "Las Condes",
    "providencia":     "Providencia",
    "vitacura":        "Vitacura",
    "nunoa":           "Ñuñoa",
    "santiago":        "Santiago",
    "maipu":           "Maipú",
    "peñalolen":       "Peñalolén",
    "penalolen":       "Peñalolén",
    "lacisterna":      "La Cisterna",
    "sanmiguel":       "San Miguel",
    "san_miguel":      "San Miguel",
    "florida":         "La Florida",
    "laflorida":       "La Florida",
    "macul":           "Macul",
    "recoleta":        "Recoleta",
    "independencia":   "Independencia",
    "quilicura":       "Quilicura",
    "pudahuel":        "Pudahuel",
    "conchali":        "Conchalí",
    "huechuraba":      "Huechuraba",
    "renca":           "Renca",
    "cerrillos":       "Cerrillos",
    "colina":          "Colina",
    "lampa":           "Lampa",
    "buin":            "Buin",
    "puente":          "Puente Alto",
    "puentealto":      "Puente Alto",
    "puente_alto":     "Puente Alto",
    "talagante":       "Talagante",
    "melipilla":       "Melipilla",
    "santiagocentro":  "Santiago Centro",
    "barnechea":       "Lo Barnechea",
    "lobarnechea":     "Lo Barnechea",
    "loespejo":        "Lo Espejo",
    "lo_espejo":       "Lo Espejo",
    "loprado":         "Lo Prado",
    "lo_prado":        "Lo Prado",
    "cerro":           "Cerro Navia",
    "cerronavia":      "Cerro Navia",
    "cerro_navia":     "Cerro Navia",
    "estacion":        "Estación Central",
    "sanjoaquin":      "San Joaquín",
    "san_joaquin":     "San Joaquín",
    "sanramón":        "San Ramón",
    "sanramon":        "San Ramón",
    "peñaflor":        "Peñaflor",
    "penaflor":        "Peñaflor",

    # ── Región del Biobío ─────────────────────────────────
    "concepcion":      "Concepción",
    "concepción":      "Concepción",
    "talcahuano":      "Talcahuano",
    "hualpén":         "Hualpén",
    "hualpen":         "Hualpén",
    "sanpedro":        "San Pedro de la Paz",
    "san_pedro":       "San Pedro de la Paz",
    "coronel":         "Coronel",
    "losangeles":      "Los Ángeles",
    "los_angeles":     "Los Ángeles",
    "losángeles":      "Los Ángeles",
    "biobio":          "Biobío",
    "bío_bío":         "Biobío",
    "arauco":          "Arauco",
    "lebu":            "Lebu",
    "curanilahue":     "Curanilahue",
    "losalamos":       "Los Álamos",
    "cañete":          "Cañete",
    "canete":          "Cañete",
    "tirua":           "Tirúa",
    "lota":            "Lota",
    "tomé":            "Tomé",
    "tome":            "Tomé",
    "penco":           "Penco",
    "hualqui":         "Hualqui",
    "santajuana":      "Santa Juana",
    "florida_bio":     "Florida",
    "yumbel":          "Yumbel",
    "cabrero":         "Cabrero",
    "laja":            "Laja",
    "nacimiento":      "Nacimiento",
    "mulchen":         "Mulchén",
    "mulchén":         "Mulchén",
    "negrete":         "Negrete",
    "santabarbara":    "Santa Bárbara",
    "quilaco":         "Quilaco",
    "quilleco":        "Quilleco",
    "altobishoften":   "Alto Biobío",
    "altobiobio":      "Alto Biobío",
    "contulmo":        "Contulmo",
    "cañete":          "Cañete",
    "tucapel":         "Tucapel",
    "antuco":          "Antuco",

    # ── Región de Ñuble ───────────────────────────────────
    "chillán":         "Chillán",
    "chillan":         "Chillán",
    "chillánviejo":    "Chillán Viejo",
    "chillanviejo":    "Chillán Viejo",
    "nuble":           "Ñuble",
    "ñuble":           "Ñuble",
    "bulnes":          "Bulnes",
    "quillon":         "Quillón",
    "quillón":         "Quillón",
    "yungay":          "Yungay",
    "laja_nuble":      "Laja",
    "sancarlos":       "San Carlos",
    "san_carlos":      "San Carlos",
    "niquen":          "Ñiquén",
    "ñiquen":          "Ñiquén",
    "sanfabián":       "San Fabián",
    "san_fabian":      "San Fabián",
    "ranquil":         "Ranquil",
    "cobquecura":      "Cobquecura",
    "coelemu":         "Coelemu",
    "portezuelo":      "Portezuelo",
    "treguaco":        "Trehuaco",
    "quirihue":        "Quirihue",
    "ninhue":          "Ninhue",
    "pemuco":          "Pemuco",
    "pinto":           "Pinto",
    "coihueco":        "Coihueco",
    "elcarmen":        "El Carmen",
    "el_carmen":       "El Carmen",
    "sanignacio":      "San Ignacio",
    "san_ignacio":     "San Ignacio",
    "tucapel_nuble":   "Tucapel",
    "elpinar":         "El Pinar",
}
